/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const ProviderID = IDL.Text;
export const MembershipType = IDL.Variant({
  'bronze' : IDL.Null,
  'gold' : IDL.Null,
  'silver' : IDL.Null,
});
export const ProviderStatus = IDL.Variant({
  'active' : IDL.Null,
  'inactive' : IDL.Null,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const WorkOrderID = IDL.Text;
export const PaymentMode = IDL.Variant({
  'upi' : IDL.Null,
  'card' : IDL.Null,
  'cash' : IDL.Null,
});
export const PaymentID = IDL.Text;
export const CustomerID = IDL.Text;
export const Aggregates = IDL.Record({
  'providerCount' : IDL.Nat,
  'completedWorkOrdersCount' : IDL.Nat,
  'activeWorkOrdersCount' : IDL.Nat,
  'customerCount' : IDL.Nat,
  'totalRevenue' : IDL.Nat,
});
export const Customer = IDL.Record({
  'id' : CustomerID,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'baseLocation' : IDL.Text,
  'mobile' : IDL.Text,
});
export const PaymentStatus = IDL.Variant({
  'pending' : IDL.Null,
  'paid' : IDL.Null,
  'failed' : IDL.Null,
});
export const Payment = IDL.Record({
  'id' : PaymentID,
  'paymentStatus' : PaymentStatus,
  'workOrderId' : WorkOrderID,
  'paymentMode' : PaymentMode,
  'amount' : IDL.Nat,
});
export const ApprovalStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const ServiceProvider = IDL.Record({
  'id' : ProviderID,
  'status' : ProviderStatus,
  'dateRegistered' : IDL.Int,
  'serviceType' : IDL.Text,
  'userId' : IDL.Principal,
  'name' : IDL.Text,
  'workPreference' : IDL.Vec(IDL.Text),
  'approvalStatus' : ApprovalStatus,
  'workingHours' : IDL.Text,
  'experienceYears' : IDL.Nat,
  'ratePerHour' : IDL.Nat,
  'workingDays' : IDL.Text,
  'mobile' : IDL.Text,
  'membershipType' : MembershipType,
  'serviceAreas' : IDL.Vec(IDL.Text),
});
export const WorkOrderStatus = IDL.Variant({
  'requested' : IDL.Null,
  'cancelled' : IDL.Null,
  'completed' : IDL.Null,
  'accepted' : IDL.Null,
  'inProgress' : IDL.Null,
});
export const WorkOrder = IDL.Record({
  'id' : WorkOrderID,
  'status' : WorkOrderStatus,
  'serviceType' : IDL.Text,
  'dateTimeRequested' : IDL.Int,
  'description' : IDL.Text,
  'customerId' : CustomerID,
  'serviceRequest' : IDL.Text,
  'assignedProviderId' : IDL.Opt(ProviderID),
  'workLocation' : IDL.Text,
});
export const ProviderEarnings = IDL.Record({
  'completedWorkOrders' : IDL.Nat,
  'totalEarnings' : IDL.Nat,
  'providerId' : ProviderID,
});
export const FetchProvidersResponse = IDL.Record({
  'providers' : IDL.Vec(ServiceProvider),
});
export const UserApprovalInfo = IDL.Record({
  'status' : ApprovalStatus,
  'principal' : IDL.Principal,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'adminApproveProvider' : IDL.Func([ProviderID], [], []),
  'adminChangeMembershipType' : IDL.Func([ProviderID, MembershipType], [], []),
  'adminChangeProviderStatus' : IDL.Func([ProviderID, ProviderStatus], [], []),
  'adminRejectProvider' : IDL.Func([ProviderID], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignProvider' : IDL.Func([WorkOrderID, ProviderID], [], []),
  'createPayment' : IDL.Func(
      [WorkOrderID, PaymentMode, IDL.Nat],
      [PaymentID],
      [],
    ),
  'createWorkOrder' : IDL.Func(
      [CustomerID, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
      [WorkOrderID],
      [],
    ),
  'getAggregates' : IDL.Func([], [Aggregates], ['query']),
  'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
  'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
  'getAllProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
  'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getMyProfile' : IDL.Func(
      [],
      [IDL.Variant({ 'provider' : ServiceProvider, 'customer' : Customer })],
      ['query'],
    ),
  'getMyWorkOrders' : IDL.Func([CustomerID], [IDL.Vec(WorkOrder)], ['query']),
  'getProviderEarnings' : IDL.Func([ProviderID], [ProviderEarnings], ['query']),
  'getProviderWorkOrders' : IDL.Func(
      [ProviderID],
      [IDL.Vec(WorkOrder)],
      ['query'],
    ),
  'getProvidersByServiceArea' : IDL.Func(
      [IDL.Text],
      [FetchProvidersResponse],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
  'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
  'registerCustomer' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text],
      [CustomerID],
      [],
    ),
  'registerProvider' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [ProviderID],
      [],
    ),
  'requestApproval' : IDL.Func([], [], []),
  'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
  'updatePaymentStatus' : IDL.Func([PaymentID, PaymentStatus], [], []),
  'updateProvider' : IDL.Func(
      [
        ProviderID,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Nat,
        IDL.Vec(IDL.Text),
      ],
      [],
      [],
    ),
  'updateWorkOrderStatus' : IDL.Func([WorkOrderID, WorkOrderStatus], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const ProviderID = IDL.Text;
  const MembershipType = IDL.Variant({
    'bronze' : IDL.Null,
    'gold' : IDL.Null,
    'silver' : IDL.Null,
  });
  const ProviderStatus = IDL.Variant({
    'active' : IDL.Null,
    'inactive' : IDL.Null,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const WorkOrderID = IDL.Text;
  const PaymentMode = IDL.Variant({
    'upi' : IDL.Null,
    'card' : IDL.Null,
    'cash' : IDL.Null,
  });
  const PaymentID = IDL.Text;
  const CustomerID = IDL.Text;
  const Aggregates = IDL.Record({
    'providerCount' : IDL.Nat,
    'completedWorkOrdersCount' : IDL.Nat,
    'activeWorkOrdersCount' : IDL.Nat,
    'customerCount' : IDL.Nat,
    'totalRevenue' : IDL.Nat,
  });
  const Customer = IDL.Record({
    'id' : CustomerID,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'baseLocation' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const PaymentStatus = IDL.Variant({
    'pending' : IDL.Null,
    'paid' : IDL.Null,
    'failed' : IDL.Null,
  });
  const Payment = IDL.Record({
    'id' : PaymentID,
    'paymentStatus' : PaymentStatus,
    'workOrderId' : WorkOrderID,
    'paymentMode' : PaymentMode,
    'amount' : IDL.Nat,
  });
  const ApprovalStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const ServiceProvider = IDL.Record({
    'id' : ProviderID,
    'status' : ProviderStatus,
    'dateRegistered' : IDL.Int,
    'serviceType' : IDL.Text,
    'userId' : IDL.Principal,
    'name' : IDL.Text,
    'workPreference' : IDL.Vec(IDL.Text),
    'approvalStatus' : ApprovalStatus,
    'workingHours' : IDL.Text,
    'experienceYears' : IDL.Nat,
    'ratePerHour' : IDL.Nat,
    'workingDays' : IDL.Text,
    'mobile' : IDL.Text,
    'membershipType' : MembershipType,
    'serviceAreas' : IDL.Vec(IDL.Text),
  });
  const WorkOrderStatus = IDL.Variant({
    'requested' : IDL.Null,
    'cancelled' : IDL.Null,
    'completed' : IDL.Null,
    'accepted' : IDL.Null,
    'inProgress' : IDL.Null,
  });
  const WorkOrder = IDL.Record({
    'id' : WorkOrderID,
    'status' : WorkOrderStatus,
    'serviceType' : IDL.Text,
    'dateTimeRequested' : IDL.Int,
    'description' : IDL.Text,
    'customerId' : CustomerID,
    'serviceRequest' : IDL.Text,
    'assignedProviderId' : IDL.Opt(ProviderID),
    'workLocation' : IDL.Text,
  });
  const ProviderEarnings = IDL.Record({
    'completedWorkOrders' : IDL.Nat,
    'totalEarnings' : IDL.Nat,
    'providerId' : ProviderID,
  });
  const FetchProvidersResponse = IDL.Record({
    'providers' : IDL.Vec(ServiceProvider),
  });
  const UserApprovalInfo = IDL.Record({
    'status' : ApprovalStatus,
    'principal' : IDL.Principal,
  });
  
  return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'adminApproveProvider' : IDL.Func([ProviderID], [], []),
    'adminChangeMembershipType' : IDL.Func(
        [ProviderID, MembershipType],
        [],
        [],
      ),
    'adminChangeProviderStatus' : IDL.Func(
        [ProviderID, ProviderStatus],
        [],
        [],
      ),
    'adminRejectProvider' : IDL.Func([ProviderID], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignProvider' : IDL.Func([WorkOrderID, ProviderID], [], []),
    'createPayment' : IDL.Func(
        [WorkOrderID, PaymentMode, IDL.Nat],
        [PaymentID],
        [],
      ),
    'createWorkOrder' : IDL.Func(
        [CustomerID, IDL.Text, IDL.Text, IDL.Text, IDL.Text],
        [WorkOrderID],
        [],
      ),
    'getAggregates' : IDL.Func([], [Aggregates], ['query']),
    'getAllCustomers' : IDL.Func([], [IDL.Vec(Customer)], ['query']),
    'getAllPayments' : IDL.Func([], [IDL.Vec(Payment)], ['query']),
    'getAllProviders' : IDL.Func([], [IDL.Vec(ServiceProvider)], ['query']),
    'getAllWorkOrders' : IDL.Func([], [IDL.Vec(WorkOrder)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getMyProfile' : IDL.Func(
        [],
        [IDL.Variant({ 'provider' : ServiceProvider, 'customer' : Customer })],
        ['query'],
      ),
    'getMyWorkOrders' : IDL.Func([CustomerID], [IDL.Vec(WorkOrder)], ['query']),
    'getProviderEarnings' : IDL.Func(
        [ProviderID],
        [ProviderEarnings],
        ['query'],
      ),
    'getProviderWorkOrders' : IDL.Func(
        [ProviderID],
        [IDL.Vec(WorkOrder)],
        ['query'],
      ),
    'getProvidersByServiceArea' : IDL.Func(
        [IDL.Text],
        [FetchProvidersResponse],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerApproved' : IDL.Func([], [IDL.Bool], ['query']),
    'listApprovals' : IDL.Func([], [IDL.Vec(UserApprovalInfo)], ['query']),
    'registerCustomer' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text],
        [CustomerID],
        [],
      ),
    'registerProvider' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [ProviderID],
        [],
      ),
    'requestApproval' : IDL.Func([], [], []),
    'setApproval' : IDL.Func([IDL.Principal, ApprovalStatus], [], []),
    'updatePaymentStatus' : IDL.Func([PaymentID, PaymentStatus], [], []),
    'updateProvider' : IDL.Func(
        [
          ProviderID,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Nat,
          IDL.Vec(IDL.Text),
        ],
        [],
        [],
      ),
    'updateWorkOrderStatus' : IDL.Func([WorkOrderID, WorkOrderStatus], [], []),
  });
};

export const init = ({ IDL }) => { return []; };