/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Aggregates {
  'providerCount' : bigint,
  'completedWorkOrdersCount' : bigint,
  'activeWorkOrdersCount' : bigint,
  'customerCount' : bigint,
  'totalRevenue' : bigint,
}
export type ApprovalStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Customer {
  'id' : CustomerID,
  'userId' : Principal,
  'name' : string,
  'baseLocation' : string,
  'mobile' : string,
}
export type CustomerID = string;
export interface FetchProvidersResponse { 'providers' : Array<ServiceProvider> }
export type MembershipType = { 'bronze' : null } |
  { 'gold' : null } |
  { 'silver' : null };
export interface Payment {
  'id' : PaymentID,
  'paymentStatus' : PaymentStatus,
  'workOrderId' : WorkOrderID,
  'paymentMode' : PaymentMode,
  'amount' : bigint,
}
export type PaymentID = string;
export type PaymentMode = { 'upi' : null } |
  { 'card' : null } |
  { 'cash' : null };
export type PaymentStatus = { 'pending' : null } |
  { 'paid' : null } |
  { 'failed' : null };
export interface ProviderEarnings {
  'completedWorkOrders' : bigint,
  'totalEarnings' : bigint,
  'providerId' : ProviderID,
}
export type ProviderID = string;
export type ProviderStatus = { 'active' : null } |
  { 'inactive' : null };
export interface ServiceProvider {
  'id' : ProviderID,
  'status' : ProviderStatus,
  'dateRegistered' : bigint,
  'serviceType' : string,
  'userId' : Principal,
  'name' : string,
  'workPreference' : Array<string>,
  'approvalStatus' : ApprovalStatus,
  'workingHours' : string,
  'experienceYears' : bigint,
  'ratePerHour' : bigint,
  'workingDays' : string,
  'mobile' : string,
  'membershipType' : MembershipType,
  'serviceAreas' : Array<string>,
}
export interface UserApprovalInfo {
  'status' : ApprovalStatus,
  'principal' : Principal,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface WorkOrder {
  'id' : WorkOrderID,
  'status' : WorkOrderStatus,
  'serviceType' : string,
  'dateTimeRequested' : bigint,
  'description' : string,
  'customerId' : CustomerID,
  'serviceRequest' : string,
  'assignedProviderId' : [] | [ProviderID],
  'workLocation' : string,
}
export type WorkOrderID = string;
export type WorkOrderStatus = { 'requested' : null } |
  { 'cancelled' : null } |
  { 'completed' : null } |
  { 'accepted' : null } |
  { 'inProgress' : null };
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'adminApproveProvider' : ActorMethod<[ProviderID], undefined>,
  'adminChangeMembershipType' : ActorMethod<
    [ProviderID, MembershipType],
    undefined
  >,
  'adminChangeProviderStatus' : ActorMethod<
    [ProviderID, ProviderStatus],
    undefined
  >,
  'adminRejectProvider' : ActorMethod<[ProviderID], undefined>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignProvider' : ActorMethod<[WorkOrderID, ProviderID], undefined>,
  'createPayment' : ActorMethod<[WorkOrderID, PaymentMode, bigint], PaymentID>,
  'createWorkOrder' : ActorMethod<
    [CustomerID, string, string, string, string],
    WorkOrderID
  >,
  'getAggregates' : ActorMethod<[], Aggregates>,
  'getAllCustomers' : ActorMethod<[], Array<Customer>>,
  'getAllPayments' : ActorMethod<[], Array<Payment>>,
  'getAllProviders' : ActorMethod<[], Array<ServiceProvider>>,
  'getAllWorkOrders' : ActorMethod<[], Array<WorkOrder>>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getMyProfile' : ActorMethod<
    [],
    { 'provider' : ServiceProvider } |
      { 'customer' : Customer }
  >,
  'getMyWorkOrders' : ActorMethod<[CustomerID], Array<WorkOrder>>,
  'getProviderEarnings' : ActorMethod<[ProviderID], ProviderEarnings>,
  'getProviderWorkOrders' : ActorMethod<[ProviderID], Array<WorkOrder>>,
  'getProvidersByServiceArea' : ActorMethod<[string], FetchProvidersResponse>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'isCallerApproved' : ActorMethod<[], boolean>,
  'listApprovals' : ActorMethod<[], Array<UserApprovalInfo>>,
  'registerCustomer' : ActorMethod<[string, string, string], CustomerID>,
  'registerProvider' : ActorMethod<
    [
      string,
      string,
      string,
      string,
      string,
      bigint,
      Array<string>,
      bigint,
      Array<string>,
    ],
    ProviderID
  >,
  'requestApproval' : ActorMethod<[], undefined>,
  'setApproval' : ActorMethod<[Principal, ApprovalStatus], undefined>,
  'updatePaymentStatus' : ActorMethod<[PaymentID, PaymentStatus], undefined>,
  'updateProvider' : ActorMethod<
    [
      ProviderID,
      string,
      string,
      string,
      string,
      string,
      bigint,
      Array<string>,
      bigint,
      Array<string>,
    ],
    undefined
  >,
  'updateWorkOrderStatus' : ActorMethod<
    [WorkOrderID, WorkOrderStatus],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];