/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface FetchProvidersResponse {
    providers: Array<ServiceProvider>;
}
export interface Aggregates {
    providerCount: bigint;
    completedWorkOrdersCount: bigint;
    activeWorkOrdersCount: bigint;
    customerCount: bigint;
    totalRevenue: bigint;
}
export interface WorkOrder {
    id: WorkOrderID;
    status: WorkOrderStatus;
    serviceType: string;
    dateTimeRequested: bigint;
    description: string;
    customerId: CustomerID;
    serviceRequest: string;
    assignedProviderId?: ProviderID;
    workLocation: string;
}
export interface Payment {
    id: PaymentID;
    paymentStatus: PaymentStatus;
    workOrderId: WorkOrderID;
    paymentMode: PaymentMode;
    amount: bigint;
}
export type PaymentID = string;
export interface Customer {
    id: CustomerID;
    userId: Principal;
    name: string;
    baseLocation: string;
    mobile: string;
}
export interface UserApprovalInfo {
    status: ApprovalStatus;
    principal: Principal;
}
export type ProviderID = string;
export interface ProviderEarnings {
    completedWorkOrders: bigint;
    totalEarnings: bigint;
    providerId: ProviderID;
}
export type WorkOrderID = string;
export interface ServiceProvider {
    id: ProviderID;
    status: ProviderStatus;
    dateRegistered: bigint;
    serviceType: string;
    userId: Principal;
    name: string;
    workPreference: Array<string>;
    approvalStatus: ApprovalStatus;
    workingHours: string;
    experienceYears: bigint;
    ratePerHour: bigint;
    workingDays: string;
    mobile: string;
    membershipType: MembershipType;
    serviceAreas: Array<string>;
}
export type CustomerID = string;
export enum ApprovalStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum MembershipType {
    bronze = "bronze",
    gold = "gold",
    silver = "silver"
}
export enum PaymentMode {
    upi = "upi",
    card = "card",
    cash = "cash"
}
export enum PaymentStatus {
    pending = "pending",
    paid = "paid",
    failed = "failed"
}
export enum ProviderStatus {
    active = "active",
    inactive = "inactive"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum WorkOrderStatus {
    requested = "requested",
    cancelled = "cancelled",
    completed = "completed",
    accepted = "accepted",
    inProgress = "inProgress"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    adminApproveProvider(id: ProviderID): Promise<void>;
    adminChangeMembershipType(id: ProviderID, membershipType: MembershipType): Promise<void>;
    adminChangeProviderStatus(id: ProviderID, status: ProviderStatus): Promise<void>;
    adminRejectProvider(id: ProviderID): Promise<void>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignProvider(workOrderId: WorkOrderID, providerId: ProviderID): Promise<void>;
    createPayment(workOrderId: WorkOrderID, paymentMode: PaymentMode, amount: bigint): Promise<PaymentID>;
    createWorkOrder(customerId: CustomerID, description: string, workLocation: string, serviceRequest: string, serviceType: string): Promise<WorkOrderID>;
    getAggregates(): Promise<Aggregates>;
    getAllCustomers(): Promise<Array<Customer>>;
    getAllPayments(): Promise<Array<Payment>>;
    getAllProviders(): Promise<Array<ServiceProvider>>;
    getAllWorkOrders(): Promise<Array<WorkOrder>>;
    getCallerUserRole(): Promise<UserRole>;
    getMyProfile(): Promise<{
        __kind__: "provider";
        provider: ServiceProvider;
    } | {
        __kind__: "customer";
        customer: Customer;
    }>;
    getMyWorkOrders(customerId: CustomerID): Promise<Array<WorkOrder>>;
    getProviderEarnings(providerId: ProviderID): Promise<ProviderEarnings>;
    getProviderWorkOrders(providerId: ProviderID): Promise<Array<WorkOrder>>;
    getProvidersByServiceArea(customerLocation: string): Promise<FetchProvidersResponse>;
    isCallerAdmin(): Promise<boolean>;
    isCallerApproved(): Promise<boolean>;
    listApprovals(): Promise<Array<UserApprovalInfo>>;
    registerCustomer(name: string, mobile: string, baseLocation: string): Promise<CustomerID>;
    registerProvider(name: string, mobile: string, serviceType: string, workingDays: string, workingHours: string, experienceYears: bigint, serviceAreas: Array<string>, ratePerHour: bigint, workPreference: Array<string>): Promise<ProviderID>;
    requestApproval(): Promise<void>;
    setApproval(user: Principal, status: ApprovalStatus): Promise<void>;
    updatePaymentStatus(paymentId: PaymentID, status: PaymentStatus): Promise<void>;
    updateProvider(providerId: ProviderID, name: string, mobile: string, serviceType: string, workingDays: string, workingHours: string, experienceYears: bigint, serviceAreas: Array<string>, ratePerHour: bigint, workPreference: Array<string>): Promise<void>;
    updateWorkOrderStatus(workOrderId: WorkOrderID, status: WorkOrderStatus): Promise<void>;
}
import type { ApprovalStatus as _ApprovalStatus, Customer as _Customer, CustomerID as _CustomerID, FetchProvidersResponse as _FetchProvidersResponse, MembershipType as _MembershipType, Payment as _Payment, PaymentID as _PaymentID, PaymentMode as _PaymentMode, PaymentStatus as _PaymentStatus, ProviderID as _ProviderID, ProviderStatus as _ProviderStatus, ServiceProvider as _ServiceProvider, UserApprovalInfo as _UserApprovalInfo, UserRole as _UserRole, WorkOrder as _WorkOrder, WorkOrderID as _WorkOrderID, WorkOrderStatus as _WorkOrderStatus } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async adminApproveProvider(arg0: ProviderID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminApproveProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminApproveProvider(arg0);
            return result;
        }
    }
    async adminChangeMembershipType(arg0: ProviderID, arg1: MembershipType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminChangeMembershipType(arg0, to_candid_MembershipType_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminChangeMembershipType(arg0, to_candid_MembershipType_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminChangeProviderStatus(arg0: ProviderID, arg1: ProviderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminChangeProviderStatus(arg0, to_candid_ProviderStatus_n3(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminChangeProviderStatus(arg0, to_candid_ProviderStatus_n3(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async adminRejectProvider(arg0: ProviderID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.adminRejectProvider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.adminRejectProvider(arg0);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n5(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignProvider(arg0: WorkOrderID, arg1: ProviderID): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignProvider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignProvider(arg0, arg1);
            return result;
        }
    }
    async createPayment(arg0: WorkOrderID, arg1: PaymentMode, arg2: bigint): Promise<PaymentID> {
        if (this.processError) {
            try {
                const result = await this.actor.createPayment(arg0, to_candid_PaymentMode_n7(this._uploadFile, this._downloadFile, arg1), arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createPayment(arg0, to_candid_PaymentMode_n7(this._uploadFile, this._downloadFile, arg1), arg2);
            return result;
        }
    }
    async createWorkOrder(arg0: CustomerID, arg1: string, arg2: string, arg3: string, arg4: string): Promise<WorkOrderID> {
        if (this.processError) {
            try {
                const result = await this.actor.createWorkOrder(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createWorkOrder(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async getAggregates(): Promise<Aggregates> {
        if (this.processError) {
            try {
                const result = await this.actor.getAggregates();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAggregates();
            return result;
        }
    }
    async getAllCustomers(): Promise<Array<Customer>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCustomers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCustomers();
            return result;
        }
    }
    async getAllPayments(): Promise<Array<Payment>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllPayments();
                return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllPayments();
            return from_candid_vec_n9(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllProviders(): Promise<Array<ServiceProvider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllProviders();
                return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllProviders();
            return from_candid_vec_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllWorkOrders(): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllWorkOrders();
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllWorkOrders();
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n31(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyProfile(): Promise<{
        __kind__: "provider";
        provider: ServiceProvider;
    } | {
        __kind__: "customer";
        customer: Customer;
    }> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyProfile();
                return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyProfile();
            return from_candid_variant_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getMyWorkOrders(arg0: CustomerID): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMyWorkOrders(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMyWorkOrders(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProviderEarnings(arg0: ProviderID): Promise<ProviderEarnings> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderEarnings(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderEarnings(arg0);
            return result;
        }
    }
    async getProviderWorkOrders(arg0: ProviderID): Promise<Array<WorkOrder>> {
        if (this.processError) {
            try {
                const result = await this.actor.getProviderWorkOrders(arg0);
                return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProviderWorkOrders(arg0);
            return from_candid_vec_n25(this._uploadFile, this._downloadFile, result);
        }
    }
    async getProvidersByServiceArea(arg0: string): Promise<FetchProvidersResponse> {
        if (this.processError) {
            try {
                const result = await this.actor.getProvidersByServiceArea(arg0);
                return from_candid_FetchProvidersResponse_n34(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getProvidersByServiceArea(arg0);
            return from_candid_FetchProvidersResponse_n34(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async isCallerApproved(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerApproved();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerApproved();
            return result;
        }
    }
    async listApprovals(): Promise<Array<UserApprovalInfo>> {
        if (this.processError) {
            try {
                const result = await this.actor.listApprovals();
                return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.listApprovals();
            return from_candid_vec_n36(this._uploadFile, this._downloadFile, result);
        }
    }
    async registerCustomer(arg0: string, arg1: string, arg2: string): Promise<CustomerID> {
        if (this.processError) {
            try {
                const result = await this.actor.registerCustomer(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerCustomer(arg0, arg1, arg2);
            return result;
        }
    }
    async registerProvider(arg0: string, arg1: string, arg2: string, arg3: string, arg4: string, arg5: bigint, arg6: Array<string>, arg7: bigint, arg8: Array<string>): Promise<ProviderID> {
        if (this.processError) {
            try {
                const result = await this.actor.registerProvider(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerProvider(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8);
            return result;
        }
    }
    async requestApproval(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.requestApproval();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.requestApproval();
            return result;
        }
    }
    async setApproval(arg0: Principal, arg1: ApprovalStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n39(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setApproval(arg0, to_candid_ApprovalStatus_n39(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updatePaymentStatus(arg0: PaymentID, arg1: PaymentStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n41(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updatePaymentStatus(arg0, to_candid_PaymentStatus_n41(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateProvider(arg0: ProviderID, arg1: string, arg2: string, arg3: string, arg4: string, arg5: string, arg6: bigint, arg7: Array<string>, arg8: bigint, arg9: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateProvider(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateProvider(arg0, arg1, arg2, arg3, arg4, arg5, arg6, arg7, arg8, arg9);
            return result;
        }
    }
    async updateWorkOrderStatus(arg0: WorkOrderID, arg1: WorkOrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateWorkOrderStatus(arg0, to_candid_WorkOrderStatus_n43(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateWorkOrderStatus(arg0, to_candid_WorkOrderStatus_n43(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
}
function from_candid_ApprovalStatus_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ApprovalStatus): ApprovalStatus {
    return from_candid_variant_n22(_uploadFile, _downloadFile, value);
}
function from_candid_FetchProvidersResponse_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _FetchProvidersResponse): FetchProvidersResponse {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_MembershipType_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _MembershipType): MembershipType {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentMode_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentMode): PaymentMode {
    return from_candid_variant_n15(_uploadFile, _downloadFile, value);
}
function from_candid_PaymentStatus_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _PaymentStatus): PaymentStatus {
    return from_candid_variant_n13(_uploadFile, _downloadFile, value);
}
function from_candid_Payment_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Payment): Payment {
    return from_candid_record_n11(_uploadFile, _downloadFile, value);
}
function from_candid_ProviderStatus_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ProviderStatus): ProviderStatus {
    return from_candid_variant_n20(_uploadFile, _downloadFile, value);
}
function from_candid_ServiceProvider_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ServiceProvider): ServiceProvider {
    return from_candid_record_n18(_uploadFile, _downloadFile, value);
}
function from_candid_UserApprovalInfo_n37(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserApprovalInfo): UserApprovalInfo {
    return from_candid_record_n38(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n32(_uploadFile, _downloadFile, value);
}
function from_candid_WorkOrderStatus_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkOrderStatus): WorkOrderStatus {
    return from_candid_variant_n29(_uploadFile, _downloadFile, value);
}
function from_candid_WorkOrder_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _WorkOrder): WorkOrder {
    return from_candid_record_n27(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_ProviderID]): ProviderID | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _PaymentID;
    paymentStatus: _PaymentStatus;
    workOrderId: _WorkOrderID;
    paymentMode: _PaymentMode;
    amount: bigint;
}): {
    id: PaymentID;
    paymentStatus: PaymentStatus;
    workOrderId: WorkOrderID;
    paymentMode: PaymentMode;
    amount: bigint;
} {
    return {
        id: value.id,
        paymentStatus: from_candid_PaymentStatus_n12(_uploadFile, _downloadFile, value.paymentStatus),
        workOrderId: value.workOrderId,
        paymentMode: from_candid_PaymentMode_n14(_uploadFile, _downloadFile, value.paymentMode),
        amount: value.amount
    };
}
function from_candid_record_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _ProviderID;
    status: _ProviderStatus;
    dateRegistered: bigint;
    serviceType: string;
    userId: Principal;
    name: string;
    workPreference: Array<string>;
    approvalStatus: _ApprovalStatus;
    workingHours: string;
    experienceYears: bigint;
    ratePerHour: bigint;
    workingDays: string;
    mobile: string;
    membershipType: _MembershipType;
    serviceAreas: Array<string>;
}): {
    id: ProviderID;
    status: ProviderStatus;
    dateRegistered: bigint;
    serviceType: string;
    userId: Principal;
    name: string;
    workPreference: Array<string>;
    approvalStatus: ApprovalStatus;
    workingHours: string;
    experienceYears: bigint;
    ratePerHour: bigint;
    workingDays: string;
    mobile: string;
    membershipType: MembershipType;
    serviceAreas: Array<string>;
} {
    return {
        id: value.id,
        status: from_candid_ProviderStatus_n19(_uploadFile, _downloadFile, value.status),
        dateRegistered: value.dateRegistered,
        serviceType: value.serviceType,
        userId: value.userId,
        name: value.name,
        workPreference: value.workPreference,
        approvalStatus: from_candid_ApprovalStatus_n21(_uploadFile, _downloadFile, value.approvalStatus),
        workingHours: value.workingHours,
        experienceYears: value.experienceYears,
        ratePerHour: value.ratePerHour,
        workingDays: value.workingDays,
        mobile: value.mobile,
        membershipType: from_candid_MembershipType_n23(_uploadFile, _downloadFile, value.membershipType),
        serviceAreas: value.serviceAreas
    };
}
function from_candid_record_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: _WorkOrderID;
    status: _WorkOrderStatus;
    serviceType: string;
    dateTimeRequested: bigint;
    description: string;
    customerId: _CustomerID;
    serviceRequest: string;
    assignedProviderId: [] | [_ProviderID];
    workLocation: string;
}): {
    id: WorkOrderID;
    status: WorkOrderStatus;
    serviceType: string;
    dateTimeRequested: bigint;
    description: string;
    customerId: CustomerID;
    serviceRequest: string;
    assignedProviderId?: ProviderID;
    workLocation: string;
} {
    return {
        id: value.id,
        status: from_candid_WorkOrderStatus_n28(_uploadFile, _downloadFile, value.status),
        serviceType: value.serviceType,
        dateTimeRequested: value.dateTimeRequested,
        description: value.description,
        customerId: value.customerId,
        serviceRequest: value.serviceRequest,
        assignedProviderId: record_opt_to_undefined(from_candid_opt_n30(_uploadFile, _downloadFile, value.assignedProviderId)),
        workLocation: value.workLocation
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    providers: Array<_ServiceProvider>;
}): {
    providers: Array<ServiceProvider>;
} {
    return {
        providers: from_candid_vec_n16(_uploadFile, _downloadFile, value.providers)
    };
}
function from_candid_record_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: _ApprovalStatus;
    principal: Principal;
}): {
    status: ApprovalStatus;
    principal: Principal;
} {
    return {
        status: from_candid_ApprovalStatus_n21(_uploadFile, _downloadFile, value.status),
        principal: value.principal
    };
}
function from_candid_variant_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
}): PaymentStatus {
    return "pending" in value ? PaymentStatus.pending : "paid" in value ? PaymentStatus.paid : "failed" in value ? PaymentStatus.failed : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
}): PaymentMode {
    return "upi" in value ? PaymentMode.upi : "card" in value ? PaymentMode.card : "cash" in value ? PaymentMode.cash : value;
}
function from_candid_variant_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    inactive: null;
}): ProviderStatus {
    return "active" in value ? ProviderStatus.active : "inactive" in value ? ProviderStatus.inactive : value;
}
function from_candid_variant_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ApprovalStatus {
    return "pending" in value ? ApprovalStatus.pending : "approved" in value ? ApprovalStatus.approved : "rejected" in value ? ApprovalStatus.rejected : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    bronze: null;
} | {
    gold: null;
} | {
    silver: null;
}): MembershipType {
    return "bronze" in value ? MembershipType.bronze : "gold" in value ? MembershipType.gold : "silver" in value ? MembershipType.silver : value;
}
function from_candid_variant_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    requested: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
}): WorkOrderStatus {
    return "requested" in value ? WorkOrderStatus.requested : "cancelled" in value ? WorkOrderStatus.cancelled : "completed" in value ? WorkOrderStatus.completed : "accepted" in value ? WorkOrderStatus.accepted : "inProgress" in value ? WorkOrderStatus.inProgress : value;
}
function from_candid_variant_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    provider: _ServiceProvider;
} | {
    customer: _Customer;
}): {
    __kind__: "provider";
    provider: ServiceProvider;
} | {
    __kind__: "customer";
    customer: Customer;
} {
    return "provider" in value ? {
        __kind__: "provider",
        provider: from_candid_ServiceProvider_n17(_uploadFile, _downloadFile, value.provider)
    } : "customer" in value ? {
        __kind__: "customer",
        customer: value.customer
    } : value;
}
function from_candid_vec_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_ServiceProvider>): Array<ServiceProvider> {
    return value.map((x)=>from_candid_ServiceProvider_n17(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_WorkOrder>): Array<WorkOrder> {
    return value.map((x)=>from_candid_WorkOrder_n26(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_UserApprovalInfo>): Array<UserApprovalInfo> {
    return value.map((x)=>from_candid_UserApprovalInfo_n37(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Payment>): Array<Payment> {
    return value.map((x)=>from_candid_Payment_n10(_uploadFile, _downloadFile, x));
}
function to_candid_ApprovalStatus_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): _ApprovalStatus {
    return to_candid_variant_n40(_uploadFile, _downloadFile, value);
}
function to_candid_MembershipType_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipType): _MembershipType {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentMode_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): _PaymentMode {
    return to_candid_variant_n8(_uploadFile, _downloadFile, value);
}
function to_candid_PaymentStatus_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): _PaymentStatus {
    return to_candid_variant_n42(_uploadFile, _downloadFile, value);
}
function to_candid_ProviderStatus_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProviderStatus): _ProviderStatus {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function to_candid_WorkOrderStatus_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrderStatus): _WorkOrderStatus {
    return to_candid_variant_n44(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: MembershipType): {
    bronze: null;
} | {
    gold: null;
} | {
    silver: null;
} {
    return value == MembershipType.bronze ? {
        bronze: null
    } : value == MembershipType.gold ? {
        gold: null
    } : value == MembershipType.silver ? {
        silver: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ProviderStatus): {
    active: null;
} | {
    inactive: null;
} {
    return value == ProviderStatus.active ? {
        active: null
    } : value == ProviderStatus.inactive ? {
        inactive: null
    } : value;
}
function to_candid_variant_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ApprovalStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ApprovalStatus.pending ? {
        pending: null
    } : value == ApprovalStatus.approved ? {
        approved: null
    } : value == ApprovalStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentStatus): {
    pending: null;
} | {
    paid: null;
} | {
    failed: null;
} {
    return value == PaymentStatus.pending ? {
        pending: null
    } : value == PaymentStatus.paid ? {
        paid: null
    } : value == PaymentStatus.failed ? {
        failed: null
    } : value;
}
function to_candid_variant_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: WorkOrderStatus): {
    requested: null;
} | {
    cancelled: null;
} | {
    completed: null;
} | {
    accepted: null;
} | {
    inProgress: null;
} {
    return value == WorkOrderStatus.requested ? {
        requested: null
    } : value == WorkOrderStatus.cancelled ? {
        cancelled: null
    } : value == WorkOrderStatus.completed ? {
        completed: null
    } : value == WorkOrderStatus.accepted ? {
        accepted: null
    } : value == WorkOrderStatus.inProgress ? {
        inProgress: null
    } : value;
}
function to_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PaymentMode): {
    upi: null;
} | {
    card: null;
} | {
    cash: null;
} {
    return value == PaymentMode.upi ? {
        upi: null
    } : value == PaymentMode.card ? {
        card: null
    } : value == PaymentMode.cash ? {
        cash: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
